//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/guardar", ReplyAction="http://tempuri.org/IService2/guardarResponse")]
        void guardar(string nom, int c1, int c2, int c3, int c4, int c5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/buscar", ReplyAction="http://tempuri.org/IService2/buscarResponse")]
        string[] buscar(string nom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/promedio", ReplyAction="http://tempuri.org/IService2/promedioResponse")]
        int promedio(int c1, int c2, int c3, int c4, int c5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Practica.ServiceReference3.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Practica.ServiceReference3.IService2>, Practica.ServiceReference3.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void guardar(string nom, int c1, int c2, int c3, int c4, int c5) {
            base.Channel.guardar(nom, c1, c2, c3, c4, c5);
        }
        
        public string[] buscar(string nom) {
            return base.Channel.buscar(nom);
        }
        
        public int promedio(int c1, int c2, int c3, int c4, int c5) {
            return base.Channel.promedio(c1, c2, c3, c4, c5);
        }
    }
}
